name: Publish to Tencent COS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: 
      group: 'xuegao-blog'
      cancel-in-progress: true

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -v --minify

      # 发布到腾讯云COS中
      - name: Upload to Tencent COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
            args: delete -r -f / && upload -r ./public/ /
            secret_id: ${{ secrets.SECRET_ID }}
            secret_key: ${{ secrets.SECRET_KEY }}
            bucket: ${{ secrets.BUCKET }}
            region: ap-guangzhou


        
